### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/pykakasi/hepburnhira2.pickle'

### ISSUE THREAD

**Issue by x86vk** [miurahr/pykakasi#22] opened 2017-12-11 09:49 UTC
Hello,

When I try the demo in the `readme.md`, it give me such an error:
```
In [9]: conv = kakasi.getConverter()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-a04f71e77951> in <module>()
----> 1 conv = kakasi.getConverter()

/usr/lib/python3.6/site-packages/pykakasi/kakasi.py in getConverter(self)
     99         if self._mode["H"] == "a":
    100             from .h2a import H2a
--> 101             self._conv["H"] = H2a(method = self._option["r"])
    102         elif self._mode["H"] == "K":
    103             from .h2k import H2K

/usr/lib/python3.6/site-packages/pykakasi/h2a.py in __init__(self, method)
     39     def __init__(self, method="Hepburn"):
     40         if method == "Hepburn":
---> 41             self._kanadict = jisyo('hepburnhira2.pickle')
     42         elif method == "Passport":
     43             self._kanadict = jisyo('passporthira2.pickle')

/usr/lib/python3.6/site-packages/pykakasi/jisyo.py in __init__(self, pklname)
     13 
     14     def __init__(self, pklname):
---> 15         dict_pkl = open(resource_filename(__name__, pklname), 'rb')
     16         self._dict = load(dict_pkl)
     17 

FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/pykakasi/hepburnhira2.pickle'

```

Is there anything that I've missed?

Thanks!

**Comment by seansaito** [comment] 2018-01-25 07:43
I also get the same error
@miurahr

**Comment by adamist521** [comment] 2018-02-01 04:41
+1

**Comment by adamist521** [comment] 2018-02-01 04:42
#15

**Comment by delihiros** [comment] 2018-03-22 13:27
same here.
seems like the `data` dirs are gone in the latest version?
I wonder if this is a root cause.
FYI, I checked out v0.22 and by running `python setup.py genkanwa && python setup.py install_lib` it worked.

**Comment by miurahr** [comment] 2018-03-24 04:47
It may happen because dictionary files are not installed correctly. As @delihiros mentions, install script should run `genkanwa` and install generated `pickled` files into lib. There may be a bug on build script.

Another approach is a way to bundle generated pickled files in repository.

**Comment by miurahr** [comment] 2018-03-25 03:26
same as #17 ?

**Comment by miurahr** [comment] 2018-03-28 12:35
Because closing #15 then close here.

**Closed by miurahr** 2018-03-28 12:35 UTC
Labels: bug, duplicate
